name: Publish package dry run on PR
'on': pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image:  google/dart:beta
    steps:
    - uses: actions/checkout@v1
    - name: Setup credentials
      run: | 
        mkdir -p ~/.pub-cache 
        cat <<EOF > ~/.pub-cache/credentials.json
        ${{ secrets.CREDENTIAL_JSON }}
        EOF
    - name: Dry run
      run: pub publish --dry-run
