name: Publish package on push
'on':
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: subosito/flutter-action@v2
      with:
        channel: 'master'
        cache: true
    - name: Setup credentials
      run: | 
        mkdir -p ~/.config/dart
        cat <<EOF > ~/.config/dart/pub-credentials.json
        ${{ secrets.CREDENTIAL_JSON }}
        EOF
    - name: Publish package
      run: flutter pub publish -f
