name: Publish package on push
'on':
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image:  dart:3.0.0-417.3.beta
    steps:
    - uses: actions/checkout@v1
    - name: Setup credentials
      run: | 
        mkdir -p ~/.pub-cache 
        cat <<EOF > ~/.pub-cache/credentials.json
        ${{ secrets.CREDENTIAL_JSON }}
        EOF
    - name: Publish package
      run: pub publish -f
